# Generated by Django 3.2.9 on 2021-11-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offlineapproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('address', models.TextField(max_length=20)),
                ('city', models.TextField(max_length=20)),
                ('ph', models.TextField(default='123', max_length=12)),
                ('mail', models.TextField(max_length=35)),
                ('item', models.TextField(max_length=20)),
                ('imo', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Offlinepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('address', models.TextField(max_length=20)),
                ('city', models.TextField(max_length=20)),
                ('ph', models.TextField(default='123', max_length=12)),
                ('mail', models.TextField(max_length=35)),
                ('item', models.TextField(max_length=20)),
                ('imo', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Onlineapproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('address', models.TextField(max_length=20)),
                ('city', models.TextField(max_length=20)),
                ('ph', models.TextField(default='123', max_length=12)),
                ('mail', models.TextField(max_length=35)),
                ('item', models.TextField(max_length=20)),
                ('imo', models.TextField(max_length=20)),
                ('credit', models.TextField(default='123', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Onlinepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('address', models.TextField(max_length=20)),
                ('city', models.TextField(max_length=20)),
                ('ph', models.TextField(default='123', max_length=12)),
                ('mail', models.TextField(max_length=35)),
                ('item', models.TextField(max_length=20)),
                ('imo', models.TextField(max_length=20)),
                ('credit', models.TextField(default='123', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=35)),
                ('otpcheck', models.TextField(max_length=6)),
            ],
        ),
    ]
